import streamlit as st
from prediction import predict_heart_disease

st.set_page_config(
    page_title="Heart Disease Prediction",
    page_icon="❤️",
    layout="wide"
)

# ===========================
# Sidebar
# ===========================

st.sidebar.title("❤️ Heart Disease Predictor")

st.sidebar.info("""

### Features Used
- Age
- Sex
- Chest Pain Type
- Resting Blood Pressure
- Cholesterol
- Fasting Blood Sugar
- Resting ECG
- Maximum Heart Rate
- Exercise Induced Angina
- Old Peak
- ST Slope

""")

# ===========================
# Title
# ===========================

st.title("❤️ Heart Disease Prediction System")

st.markdown(
"""
Enter the patient's clinical information below and click **Predict**.
"""
)

st.divider()

left, right = st.columns(2)

# ===========================
# Left Column
# ===========================

with left:

    age = st.slider(
        "Age",
        28,
        77,
        50,
        help="Patient age in years."
    )

    sex = st.selectbox(
        "Sex",
        ["M", "F"]
    )

    chest_pain = st.selectbox(
        "Chest Pain Type",
        ["ATA", "NAP", "ASY", "TA"],
        help="""
ATA = Atypical Angina

NAP = Non-Anginal Pain

ASY = Asymptomatic

TA = Typical Angina
"""
    )

    resting_bp = st.slider(
        "Resting Blood Pressure (mmHg)",
        80,
        200,
        120
    )

    cholesterol = st.slider(
        "Cholesterol (mg/dL)",
        100,
        650,
        200
    )

# ===========================
# Right Column
# ===========================

with right:

    fasting_bs = st.selectbox(
        "Fasting Blood Sugar",
        [0, 1],
        help="1 = >120 mg/dL"
    )

    resting_ecg = st.selectbox(
        "Resting ECG",
        ["Normal", "ST", "LVH"]
    )

    max_hr = st.slider(
        "Maximum Heart Rate",
        60,
        202,
        150
    )

    exercise_angina = st.selectbox(
        "Exercise Induced Angina",
        ["N", "Y"]
    )

    oldpeak = st.slider(
        "Old Peak",
        -2.6,
        6.2,
        1.0,
        0.1
    )

    st_slope = st.selectbox(
        "ST Slope",
        ["Up", "Flat", "Down"]
    )

st.divider()

# ===========================
# Predict Button
# ===========================

if st.button("🔍 Predict", use_container_width=True):

    input_data = {
        "Age": age,
        "Sex": sex,
        "ChestPainType": chest_pain,
        "RestingBP": resting_bp,
        "Cholesterol": cholesterol,
        "FastingBS": fasting_bs,
        "RestingECG": resting_ecg,
        "MaxHR": max_hr,
        "ExerciseAngina": exercise_angina,
        "Oldpeak": oldpeak,
        "ST_Slope": st_slope
    }

    prediction, confidence = predict_heart_disease(input_data)

    st.divider()

    st.subheader("Prediction Result")

    if prediction == 1:

        st.error("⚠ High Risk of Heart Disease")

    else:

        st.success("✅ Low Risk of Heart Disease")

    st.metric(
        label="Prediction Confidence",
        value=f"{confidence:.2f}%"
    )

    st.progress(int(confidence))

    st.info("""
⚠️ This prediction is generated by a Machine Learning model and is intended for educational purposes only.
Please consult a qualified healthcare professional for medical advice.
""")

